---
title: "ethnicity"
author: "Pac"
date: '2022-11-08'
output: html_document
---

```{r}
library("tidyverse")
library("randomForest")
library("ranger")
library("cowplot")
set.seed(1122)
```

```{r}
fulldata <- read.csv("data/rt_tidy.csv")
olddata <- read.csv("data/TrainSet.csv")
```

```{r}
ranger_model <- fulldata %>% 
  drop_na(c(sex,age,country)) %>% 
  mutate(Race = as.factor(Race),
         Gender = as.factor(Gender),
         trait = as.factor(trait),
         stim_id = as.factor(stim_id),
         sex = as.factor(sex),
         country = as.factor(country),
         language = as.factor(language),
         lab = as.factor(lab),
         user_id = as.factor(user_id)) %>% 
  mutate(rating = as.numeric(rating),
         rt = as.numeric(rt), 
         Age = as.numeric(Age),
         age = as.numeric(age)
         ) %>% 
  dplyr::select(rating, rt, Race, Gender, Age, trait, stim_id, sex, age, country, language, lab, user_id)

rf <- ranger(dependent.variable.name = "rating",
                       data = ranger_model, # 指定训练数据集
                       num.trees = 1000, # 指定树的数量
                       mtry = 3, # 指定每个树节点随机选择的属性数量
                       importance = "permutation",  # 指定特征重要性估计的方法
                       sample.fraction = 0.7,  # 指定随机采样的比例
                       verbose = TRUE
                       )

```

```{r}
rf_importance <- importance(rf)
importance_df <- data.frame(feature = names(rf$variable.importance),
                            importance = rf$variable.importance)
new <- 
  ggplot(data = importance_df, aes(x = reorder(feature,importance), y = importance)) +
  geom_bar(stat = "identity", fill = "steelblue", width = 0.5) +
  #geom_point(stat = "identity", color = "steelblue") +
  geom_hline(yintercept = abs(min(rf_importance)), linetype = "dotted", color = "red", linewidth = 0.8) +
  ggtitle("Feature Importance Plot") +
  coord_flip()+
  xlab("Features") +
    #geom_text(aes(label = importance), size=3, hjust = 0.8)+
  ylab("Importance") +
  theme_classic()
new
```




