---
title: "ethnicity"
author: "Pac"
date: '2022-11-08'
output: html_document
---

```{r}
library("tidyverse")
library("xgboost")
library("randomForest")
library("ranger")
library("cowplot")
set.seed(1122)
```

```{r}
fulldata <- read.csv("data/rt_tidy.csv")
olddata <- read.csv("data/TrainSet.csv")
```

###使用randomForest包实现随机森林，跑不出来
```{r}

#rating_randomforest <- fulldata %>% 
#  select(rating, rt, Race, Gender, Age, trait)
#rf_model <- randomForest(rating~rt+Race+Gender+Age+trait, data = rating_randomforest, ntree = 100, mtry = 3, importance = TRUE)

```

使用ranger包实现随机森林
#https://www.coder.work/article/4762286，这篇blog里有谈到为什么使用不同的包做#https://arikuncoro.xyz/blog/data-science/r-python-sql-linux/the-comparison-between-randomforest-and-ranger/ 谈到了为什么运行速度会有差异
#ranger: A Fast Implementation of Random Forests for High Dimensional Data in C++ and R DOI:10.18637/jss.v077.i01 介绍了Ranger包
```{r}
ranger_model <- fulldata %>% 
  dplyr::select(rating, rt, Race, Gender, Age, trait)
rf <- ranger(dependent.variable.name = "rating",
                       data = ranger_model, # 指定训练数据集
                       num.trees = 1000, # 指定树的数量
                       mtry = 3, # 指定每个树节点随机选择的属性数量
                       importance = "permutation",  # 指定特征重要性估计的方法
                       sample.fraction = 0.7,  # 指定随机采样的比例
                       verbose = TRUE
                       )

```

```{r}
rf_importance <- importance(rf)
importance_df <- data.frame(feature = names(rf$variable.importance),
                            importance = rf$variable.importance)
new <- ggplot(importance_df, aes(x = reorder(feature,importance), y = importance)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  ggtitle("Feature Importance Plot") +
  coord_flip()+
  xlab("Features") +
  geom_text(aes(label = importance), size=3, hjust = 0.8)+
  ylab("Importance")
new
```

```{r}
oldranger_model <- olddata %>% 
  dplyr::select(rating, rt, Race, Gender, Age, trait)
oldrf <- ranger(dependent.variable.name = "rating",
                       data = oldranger_model, # 指定训练数据集
                       num.trees = 1000, # 指定树的数量
                       mtry = 3, # 指定每个树节点随机选择的属性数量
                       importance = "permutation",  # 指定特征重要性估计的方法
                       sample.fraction = 0.7,  # 指定随机采样的比例
                       verbose = TRUE
                       )
```

```{r}
oldrf_importance <- importance(oldrf)
oldimportance_df <- data.frame(feature = names(oldrf$variable.importance),
                            importance = oldrf$variable.importance)
old <- ggplot(oldimportance_df, aes(x = reorder(feature,importance), y = importance)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  ggtitle("Feature Importance Plot") +
  coord_flip()+
  xlab("Features") +
  geom_text(aes(label = importance), size=3, hjust = 0.8)+
  ylab("Importance")
old
```

```{r}
plot_grid(new, old, nrow = 1)
```


