---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r packages}
library(tidyverse)
library(ggplot2)
#install.packages("infotheo")
library(infotheo)
#install.packages("dplyr")
library(dplyr)
```

```{r temp}
gc()
```


```{r tidying}
#load data
rt_rating = read.csv("data/psa001_ratings_raw_subset.csv")
rt_rating_positive = rt_rating[which(rt_rating$rt>0), ] 
stim_info = read.csv("data/stim_info.csv")

#join rt_rating with necessary stimulus information
rt_rating_pos_full = full_join (rt_rating_positive, stim_info, by = 'stim_id')

#know the distribution
ggplot(data = rt_rating_pos_full, 
       mapping = aes(x=rating, y = rt,))+
       geom_boxplot()

summary(rt_rating_pos_full$rt)

#exclude extreme variables
rt_tidy = filter(rt_rating_pos_full, rt<5000)

write.csv(rt_tidy, "data/rt_tidy.csv")

```



```{r}
#randomly choose a part of data
set.seed(100)
train <- sample(nrow(rt_rating_pos_full), 0.1*nrow(rt_rating_pos_full), replace = FALSE)
TrainSet <- rt_rating_pos_full[train,]
ValidSet <- rt_rating_pos_full[-train,]

write.csv(TrainSet, file = "data/TrainSet.csv")

#rt_rating_break <-discretize(rt_rating_positive$rt,"equalfreq",10)
#memory.limit(size = 50000)        
#rt_ra_cls = merge(rt_rating_break, rt_rating_positive)
```



