---
title: "Untitled"
author: "Pac"
date: "2023-06-20"
output: html_document
---
```{r}
pacman::p_load(tidyverse, bruceR, DataExplorer)
```

```{r}
data <- read.csv("./data/rt_tidy.csv")
regions <- read.csv("data/regions.csv")
data_region <- fulldata %>% 
  mutate(lab  = substr(lab,1,nchar(lab)-4)) %>% 
  mutate(country = lab) %>% 
  left_join(regions, by = "country")
colnames(data)
```

```{r}
data %>% 
  select(trait, rt, rating, age, Age, log_rt) %>% 
  group_by(trait) %>% 
  #filter(trait == "attractive") %>% 
  na.omit() %>% 
  bruceR::Corr()
```

```{r}
data %>% 
  ggplot(aes(x = rt))+
  geom_density()
```


```{r}
lm1 = lm(rating ~ rt + age, data = data)
model_summary(lm1)
```
```{r}
region_model <- lmer(rating ~ rt + (rt | region.x), data = data_region)

#tightness_model <- lmer(VC ~ H_Ccentered + V_Ccentered + tight_centered + H_Ccentered*tight_centered + V_Ccentered*tight_centered + (1 + H_Ccentered + V_Ccentered | province), data = hierarchy_model)

HLM_summary(region_model)
```




















